miniio:
  bucket:
    host: ${PICPAYBANK_REGULATORY_S3_HOST}
    accessKey: ${PICPAYBANK_REGULATORY_S3_ACCESS_KEY}
    secretKey: ${PICPAYBANK_REGULATORY_S3_SECRET_KEY}
    region: ${PICPAYBANK_REGULATORY_S3_REGION}
    bucketName: ${PICPAYBANK_ACCOUNTING_GATEWAY_S3_STORAGE_NAME}